apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  # TODO: Add Service Account variables
  template:
    spec:
      containers:
        - env:
          - name: AMQP_HOST
            value: broker-amq-amqp
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
